# Default configuration
default:
   directory: /tmp/traq_test
   user: taq
   list: 
   - Rakefile
   - config.ru
   - Gemfile
   - - config/application.rb
   - - config/environment.rb
   - - config/initializers/**/*
   - - config/environments/production.rb
   - - config/locales/**/*
   - - config/routes.rb
   - - app/**/*
   - - db/migrate/**/*
   - - public/javascripts/**/*
   - - public/stylesheets/**/*
   - - lib/**/*
   - - bin/**/*
   - - public/images/**/*
     - public/images/uploads/**/*
   password: fill your password here
   host: localhost
   server: passenger
   shell: bash -l -c 
custom:
   directory: /tmp/traq_test_custom
   user: taq
   list: 
   - Rakefile
   - config.ru
   - Gemfile
   - - config/application.rb
   - - config/environment.rb
   - - config/initializers/**/*
   - - config/environments/production.rb
   - - config/locales/**/*
   - - config/routes.rb
   - - app/**/*
   - - db/migrate/**/*
   - - public/javascripts/**/*
   - - public/stylesheets/**/*
   - - lib/**/*
   - - bin/**/*
   - - public/images/**/*
     - public/images/uploads/**/*
   password: fill your password here
   host: localhost
   shell: bash -l -c 
