# Default configuration--- 
:directory: /tmp/traq_test
:ignore: 24
:user: taq
:list: 
- - app/**/*
- - config/initializers/**/*
- - config/environments/production.rb
- - db/migrate/**/*
- - public/javascripts/**/*
- - public/stylesheets/**/*
- - config/locales/**/*
- - config/routes.rb
- - lib/**/*
- - public/images/**/*
  - public/images/uploads/**/*
:password: fill your password here
:host: localhost
:server: passenger
