# Default configuration--- 
directory: /tmp/traq_test
user: taq
list: 
- Rakefile
- config.ru
- Gemfile
- - config/application.rb
- - config/environment.rb
- - config/initializers/**/*
- - config/environments/production.rb
- - config/locales/**/*
- - config/routes.rb
- - config/boot.rb
- - config/database.yml
- - config/secrets.yml
- - app/**/*
- - db/migrate/**/*
- - db/seeds.rb
- - public/javascripts/**/*
- - public/stylesheets/**/*
- - lib/**/*
- - bin/**/*
- - public/images/**/*
  - public/images/uploads/**/*
password: fill your password here
host: localhost
server: passenger
shell: bash -l -c 
