# Sample configuration--- 
directory: /tmp/traq_test
user: taq
list: 
- Rakefile
- config.ru
- Gemfile
- - config/application.rb
- - config/environment.rb
- - config/initializers/**/*
- - config/environments/production.rb
- - config/locales/**/*
- - config/routes.rb
- - config/storage.yml
- - app/**/*
- - db/migrate/**/*
- - public/javascripts/**/*
- - public/stylesheets/**/*
- - lib/**/*
- - public/404.html
- - public/422.html
- - public/500.html
- - public/favicon.ico
- - public/robots.txt
- - public/images/**/*
  - public/images/uploads/**/*
  - public/images/themes/**/*
password: fill your password here
host: localhost
server: passenger
shell: bash -l -c 
